name: Tự động cập nhật Submodule AI cho Repo Cha

on:
  push:
    branches: [ "dev" ] # Lắng nghe sự thay đổi trên nhánh main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy code của Repo Cha về
        uses: actions/checkout@v4
        with:
          repository: thanhh2310/ecommerce_AI
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git submodule update --remote --recursive

          git add ai-chatbot-service
          git commit -m "🤖 Auto update AI submodule" || echo "No changes"
          git push