name: Tự động cập nhật Submodule AI cho Repo Cha

on:
  push:
    branches: [ "dev" ] # Lắng nghe sự thay đổi trên nhánh main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy code của Repo Cha về
        uses: actions/checkout@v4
        with:
          # LƯU Ý: Thay 'DATN' bằng 'ecommerce_AI' nếu kho cha thực sự của bạn tên là ecommerce_AI
          repository: thanhh2310/ecommerce_AI 
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: Cập nhật code mới của thư mục AI và push lên Repo Cha
        run: |
          # 1. Định danh cho Robot trước tiên
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # 2. Đi thẳng vào thư mục AI, lấy thông tin và kéo nhánh dev
          cd ai-chatbot-service
          git fetch origin
          git checkout dev
          git pull origin dev
          cd ..
          
          # 3. Commit và Push lên kho cha DATN
          git add ai-chatbot-service
          git commit -m "🤖 Tự động cập nhật AI Chatbot từ nhánh dev" || echo "Không có sự thay đổi nào"
          git push